version: '3.8'

services:
    valuesoft:
        image: adoptopenjdk
#        restart: always
        volumes:
            - ./:/app
        working_dir: /app
        command: sh gradlew clean runServer
        env_file:
            -   "./configs/${TASK}.yml"
        environment:
#            JVM_OPTS: -Xmx900m -Xms900m -XX:MaxPermSize=900m
            TASK: "${TASK}"
            TELEGRAM_TOKEN: 6123168689:AAGfgNNggz-jGrPGuHQTEQ7cPhzkQSnhEcI
