version: '3.8'

services:
    valuesoft:
        image: adoptopenjdk
#        restart: always
        volumes:
            - ./:/app
        working_dir: /app
        command: sh gradlew clean runServer
        env_file:
            -   "./configs/${TASK}.yml"
        environment:
            TASK: "${TASK}"